# Stage 1: Build
FROM node:20.11.0-alpine AS build
WORKDIR /usr/src/app
COPY package.json/* .
# Copy package.json and yarn.lock


FROM build as development
RUN npm install --silent
# Copy the rest of the application code
COPY . .

# Build the application
# RUN yarn build # Uncomment if you have a build step [TypeScript]

# Stage 2: Production
FROM base AS production
RUN npm install --silent
COPY . .
RUN npm run build

FROM nginx:alpine AS runtime
COPY nginx/nginx.conf /etc/nginx/nginx/conf
# Copy only the build artifacts and runtime dependencies
COPY --from=build /usr/src/app/ ./
# COPY --from=build /usr/src/app/dist ./dist # Use this line if you have built files [TypeScript]

# Expose the port and define the command to run the application
EXPOSE 3001
RUN chown -R node /usr/src/app

# CMD [ "node", "dist/app.js" ] # Use this line if you are working with TS
CMD ["node", "src/app.js"]