dockerfile# =======================================================
# 1. Base Image: Install dependencies
# =======================================================
FROM node:22-alpine AS base
WORKDIR /usr/src/app
# Next.js telemetry can be disabled to speed up builds
ENV NEXT_TELEMETRY_DISABLED=1
COPY ["package.json", "package-lock.json*", "./"]

# # =======================================================
# # 2. Dev Stage: Local development with hot-reloading
# # =======================================================
FROM base AS development
# ENV NODE_ENV=development
# RUN npm install --silent
# COPY . .
# # Next.js dev server runs on 3000 by default
# EXPOSE 3000 
# CMD ["npm", "run", "dev"]

# # =======================================================
# # 3. Build Stage: Compile the Next.js application
# # =======================================================
# FROM base AS builder
# COPY . .
# RUN npm ci --silent
# # Generates production code inside the .next folder
# RUN npm run build 

# # =======================================================
# # 4. Prod Runtime Stage: Lightweight Node environment
# # =======================================================
# FROM node:22-alpine AS runtime
# WORKDIR /usr/src/app

# ENV NODE_ENV=production
# ENV NEXT_TELEMETRY_DISABLED=1
# # Next.js binds to localhost by default; 0.0.0.0 exposes it outside the container
# ENV PORT=3000
# ENV HOSTNAME="0.0.0.0"

# # Create a non-root system user for security
# RUN addgroup --system --gid 1001 nodejs
# RUN adduser --system --uid 1001 nextjs

# # Copy only the compiled build and minimum runtime files from builder
# COPY --from=builder /usr/src/app/public ./public
# COPY --from=builder --chown=nextjs:nodejs /usr/src/app/.next/standalone ./
# COPY --from=builder --chown=nextjs:nodejs /usr/src/app/.next/static ./.next/static

# # Switch away from root user
# USER nextjs

# EXPOSE 3000

# # Start the standalone Next.js server directly using Node
# CMD ["node", "server.js"]



# FROM base as production
# ENV NODE_ENV=production
# RUN npm install --production --silent && mv node_nodules ../
# COPY . .
# EXPOSE 5001
# RUN chown -R node /usr/src/app
# USER node
# RUN ["npm","start"]