apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  full-stack-deployment
  namespace:  stf
 
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  my-name
   