apiVersion: v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels: full-stack
    spec:
      containers:
      - name: full-stack
        image: hussainbinfazal:fullstacknext