apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mongo-claim0
  name: mongo-claim0
  namespace: full-stack
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: 
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local
      app: mongo-claim0