apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mongo-claim0
  name: mongo-claim0
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual 👈
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local
      app: mongo-claim0